Indutry4.0/Controllers/FeedbackPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Indutry4._0.Data;
using Indutry4._0.Models;
using Microsoft.AspNetCore.Authorization;

namespace Indutry4._0.Controllers
{
    public class FeedbackPostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FeedbackPostsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: FeedbackPosts
        public async Task<IActionResult> Index()
        {
            return View(await _context.FeedbackPost.ToListAsync());
        }

        // GET: FeedbackPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedbackPost = await _context.FeedbackPost
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feedbackPost == null)
            {
                return NotFound();
            }

            return View(feedbackPost);
        }

        // GET: FeedbackPosts/Create
        [Authorize(Roles = "Manager, RegisteredUser")]
        public IActionResult Create()
        {
            FeedbackPost fd = new FeedbackPost();
            fd.Date = DateTime.Now;
            fd.UserName = User.Identity.Name;

            return View(fd);
        }

        // POST: FeedbackPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager, RegisteredUser")]
        public async Task<IActionResult> Create([Bind("Id,Date,UserName,Heading,StarRating,Feedback,Agree,Disagree,CompanyOrganizationName,canIncreaseAgree,canIncreaseDisagree")] FeedbackPost feedbackPost)
        {
            if (ModelState.IsValid)
            {
                _context.Add(feedbackPost);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("companiesOrganizations", "Home");
            }
            return View(feedbackPost);
        }

        // GET: FeedbackPosts/Edit/5
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedbackPost = await _context.FeedbackPost.FindAsync(id);
            if (feedbackPost == null)
            {
                return NotFound();
            }
            return View(feedbackPost);
        }

        // POST: FeedbackPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,UserName,Heading,StarRating,Feedback,Agree,Disagree,CompanyOrganizationName,canIncreaseAgree,canIncreaseDisagree")] FeedbackPost feedbackPost)
        {
            if (id != feedbackPost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(feedbackPost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeedbackPostExists(feedbackPost.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("companiesOrganizations", "Home");
            }
            return View(feedbackPost);
        }

        // GET: FeedbackPosts/Delete/5
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedbackPost = await _context.FeedbackPost
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feedbackPost == null)
            {
                return NotFound();
            }

            return View(feedbackPost);
        }

        // POST: FeedbackPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var feedbackPost = await _context.FeedbackPost.FindAsync(id);
            _context.FeedbackPost.Remove(feedbackPost);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToAction("companiesOrganizations", "Home");
        }

        private bool FeedbackPostExists(int id)
        {
            return _context.FeedbackPost.Any(e => e.Id == id);
        }

        public async Task<IActionResult> IncreaseAgree(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedbackPost = await _context.FeedbackPost.FindAsync(id);
            if (feedbackPost == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                //try
                //{
                //    feedbackPost.Agree++;

                //    _context.Update(feedbackPost);
                //    await _context.SaveChangesAsync();
                //}
                try
                {
                    if(User.Identity.IsAuthenticated && feedbackPost.CanIncreaseAgree)
                    {
                        feedbackPost.Agree++;
                        feedbackPost.CanIncreaseAgree = false;
                        _context.Update(feedbackPost);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeedbackPostExists(feedbackPost.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("companiesOrganizations", "Home");
                //return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("companiesOrganizations", "Home");
            //return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> IncreaseDisagree(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedbackPost = await _context.FeedbackPost.FindAsync(id);
            if (feedbackPost == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                //try
                //{
                //    feedbackPost.Disagree++;

                //    _context.Update(feedbackPost);
                //    await _context.SaveChangesAsync();
                //}
                try
                {
                    if (User.Identity.IsAuthenticated && feedbackPost.CanIncreaseDisagree)
                    {
                        feedbackPost.Disagree++;
                        feedbackPost.CanIncreaseDisagree = false;
                        _context.Update(feedbackPost);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeedbackPostExists(feedbackPost.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("companiesOrganizations", "Home");
                //return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("companiesOrganizations", "Home");
            //return RedirectToAction(nameof(Index));
        }

    }
    
}

Indutry4.0/Controllers/HomeController.cs
using Indutry4._0.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
//using AspNetUserRolesEntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Indutry4._0.Data;

namespace Indutry4._0.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Home()
        {
            return View();
        }

        //public IActionResult CompaniesOrganizations()
        //{
        //    return View();
        //}

        public async Task<IActionResult> CompaniesOrganizations()
        {
            if (!User.Identity.IsAuthenticated)
            {
                foreach (var post in _context.FeedbackPost)
                {
                    post.CanIncreaseAgree = true;
                    post.CanIncreaseDisagree = true;
                }
                await _context.SaveChangesAsync();
            }

            var allFeedbakPosts = from result in _context.FeedbackPost
                                 orderby result.Date descending
                                 select result;

            return View(await allFeedbakPosts.ToListAsync());

            //return View(await _context.FeedbackPost.ToListAsync());
        }


        public async Task<IActionResult> EmergingTechnologiesAsync()
        {
            var allFeedbakPosts = from result in _context.FeedbackPost
                                  orderby result.Date descending
                                  select result;

            return View(await allFeedbakPosts.ToListAsync());
        }

        public IActionResult ContactAbout()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Indutry4.0/Views/Home/ContactAbout.cshtml
@model IEnumerable<Indutry4._0.Models.FeedbackPost>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<!--1. Background and Title-->
<section id="contacPage_backround">
    <!--1st background image-->
    <header id="header2"> Contact and About</header><!--large header-->
    <p id="intro">
        Industry 4.0 is the digital transformation of manufacturing/production and related industries and value creation processes.
        Industry 4.0 is used interchangeably with the fourth industrial revolution and represents a new stage in the organization and control of the industrial value chain.
        (https://www.i-scoop.eu/industry-4-0/)
    </p>
</section>

<section class="row" id="contact">

    <!--6 images for 6 companies and organisations here-->
    <!--use javascript or jquery to add them-->
    <!--good for extension if there are more companies and organisations-->

</section>

Indutry4.0/Views/Home/HomePage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    //ViewData["Title"] = "Home Page";
}
<h1>@ViewData["Title"]</h1>

<div id="homepage">
    <div @*class="container-fluid"*@>
        <!-- for full width layout-->
        <article>
            <!--1. for search provider e.g. Google and Bing-->

            <section id="homepage_background1">
                <!--1st background image-->
                <header id="title"> Industry 4.0</header><!--large header-->
                <p id="intro">
                    Industry 4.0 is a name given to the current trend
                    of automation and data exchange in manufacturing technologies.
                    It includes cyber-physical systems, the Internet of things,
                    cloud computing and cognitive computing. Industry 4.0 is
                    commonly referred to as the fourth industrial revolution.
                    <br>-Wikipedia-
                </p>
            </section>

            <!--2.Images-->
            <div class="padding" class="container-fluid">
                <section class="row" id="tech">

                    <!--6 images for 6 companies and organisations here-->
                    <!--use javascript or jquery to add them-->
                    <!--good for extension if there are more companies and organisations-->

                </section>
            </div>

            <section id="homepage_background2">
                <!--2nd background image-->
                <p id="center-paragraph"></p>
            </section>

        </article>
        
        <article>
            <!--for search providers e.g. Google and bing-->
        </article>
    </div>
</div>

Indutry4.0/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@*<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>*@


    <!-- for full width layout-->

    <!--1. for search provider e.g. Google and Bing-->

    <section id="homepage_background1">
        <!--1st background image-->
        <header id="title"> Industry 4.0</header><!--large header-->
        <p id="intro">
            Industry 4.0 is a name given to the current trend
            of automation and data exchange in manufacturing technologies.
            It includes cyber-physical systems, the Internet of things,
            cloud computing and cognitive computing. Industry 4.0 is
            commonly referred to as the fourth industrial revolution.
            <br>-Wikipedia-
        </p>
    </section>

    <!--2.Images-->
    <div class="padding" @*class="container"*@>
        <section class="row" id="tech">

            <!--6 images for 6 companies and organisations here-->
            <!--use javascript or jquery to add them-->
            <!--good for extension if there are more companies and organisations-->

        </section>
    </div>

    <section id="homepage_background2">
        <!--2nd background image-->
        <p id="center-paragraph"></p>
    </section>

    <section>
        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">
            <ul class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="2" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="3" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="4" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="5" class="active"></li>

            </ul>
            <!--The slider-->
            <div class="carousel-inner">
                <!--Slider IBM-->
                <div class="carousel-item active">
                    <img src="../images/Homepage/ibm.jpg" alt="IBM" class="img-fluid" style="width: 100%;" />
                    <div class="carousel-caption" role="option">
                        <p class="stitle">
                            IBM<br />
                            @*<a class="btn btn-info" href="https://www.ibm.com/us-en/">
                            Learn More
                        </a>*@
                        </p>
                        <a class="btn btn-info" href="https://www.ibm.com/us-en/">
                            Learn More
                        </a>
                    </div>
                </div>
                <!--Slider Amazon-->
                <div class="carousel-item">
                    <img src="../images/Homepage/amazon.jpg" alt="Amazon" class="img-fluid" style="width: 100%;" />
                    <div class="carousel-caption" role="option">
                        <p class="stitle">
                            Amazon<br />
                            @*<a class="btn btn-info" href="https://aws.amazon.com/manufacturing/">
                            Learn More
                        </a>*@
                        </p>
                        <a class="btn btn-info" href="https://aws.amazon.com/manufacturing">
                            Learn More
                        </a>    
                    </div>
                </div>

                <div class="carousel-item">
                    <img src="images/Homepage/google.jpg" alt="google" class="img-fluid" style="width: 100%;" />
                    <div class="carousel-caption" role="option">
                        <p class="stitle">
                            Google<br />
                            @*<a class="btn btn-info" href="https://ai.google/">
                            Learn More
                        </a>*@
                        </p>
                        <a class="btn btn-info" href="https://ai.google/">
                            Learn More
                        </a>
                    </div>
                </div>

                <div class="carousel-item">
                    <img src="images/Homepage/microsoft.jpg" alt="microsoft" class="img-fluid" style="width: 100%;" />
                    <div class="carousel-caption" role="option">
                        <p class="stitle">
                            Microsoft<br />
                            @*<a class="btn btn-info" href="https://www.microsoft.com/en-us/ai?activetab=pivot1%3aprimaryr6">
                            Learn More
                        </a>*@
                        </p>
                        <a class="btn btn-info" href="https://www.microsoft.com/en-us/ai?activetab=pivot1%3aprimaryr6">
                            Learn More
                        </a>
                    </div>
                </div>

                <div class="carousel-item">
                    <img src="images/Homepage/csiro.jpg" alt="csiro" class="img-fluid" style="width: 100%;" />
                    <div class="carousel-caption" role="option">
                        <p class="stitle">
                            Csiro<br />
                            @*<a class="btn btn-info" href="https://www.csiro.au/">
                            Learn More
                        </a>*@
                        </p>
                        <a class="btn btn-info" href="https://www.csiro.au/">
                            Learn More
                        </a>
                    </div>
                </div>


                <div class="carousel-item">
                    <img src="images/Homepage/department.jpg" alt="department" class="img-fluid" style="width: 100%;" />
                    <div class="carousel-caption" role="option">
                        <p class="stitle">
                            Department of Industry, Science, Energy and Resuources<br />
                            @*<a class="btn btn-info" href="https://www.industry.gov.au/">
                            Learn More
                        </a>*@
                        </p>
                        <a class="btn btn-info" href="https://www.industry.gov.au/">
                            Learn More
                        </a>
                    </div>
                </div>
            </div>
            <!--left Right buttons-->
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </section>
        

Indutry4.0/Views/Home/companiesOrganizations.cshtml
@model IEnumerable<Indutry4._0.Models.FeedbackPost>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



<article>

    <!--1. Background and Title-->
    <section id="companiesPage_background1">
        <!--1st background image-->
        <header id="header2"> Companies and Organizations</header><!--large header-->
        <p id="intro">
            The Industry 4.0 market is forecasted to reach $1 trillion by 2030,
            dominated by global technology giants including Alphabet-Google, HP,
            Samsung, IBM, NEC, Microsoft, and more. According to the new 4-volume
            report by HSRC: Global Industry 4.0 Market & Technologies 2018-2023,
            the Industry 4.0 market will reach $214B by 2023
            (https://www.prnewswire.com/news-releases/global-tech-giants-to-lead-the-industry-40-revolution-300585640.html)
            <br>-Wikipedia-
        </p>
    </section>

    <!--2.Images-->
    @*<div class="padding" class="container-fluid" >*@
        <section class="row" id="companies">

            <!--6 images for 6 companies and organisations here-->
            <!--use javascript or jquery to add them-->
            <!--good for extension if there are more companies and organisations-->

        </section>
    @*</div>*@


</article>

<section>
    <h1 id="feedback">Feedback</h1>
</section>

<section>
    @if (User.Identity.IsAuthenticated)
    {
        <div style="text-align:center;">
            <a href="~/FeedbackPosts/Create/" class="btn btn-info">Submit your feedback</a>
        </div>
    }
    else
    {
        <div style="text-align:center;">
            Please <a href="~/Identity/Account/Login?returnUrl=~/Home/companiesOrganizations">login</a> or
            <a href="~/Identity/Account/Register?returnUrl=~/Home/companiesOrganizations">create an account</a>
            to submit your feedback on this page
        </div>
    }

    <hr />


</section>

<section>
    @foreach (var item in Model)
    {
        <h2>@Html.DisplayFor(modelItem => item.Heading)</h2>
        <p>&#64;@Html.DisplayFor(modelItem => item.CompanyOrganizationName)</p>
        @*<p>@Html.DisplayFor(modelItem => item.StarRating)</p>*@
        <p>
            @{
                for (int i = 0; i < item.StarRating; i++)
                {
                    <span style="color: #f8bd08; ">&#x2605;</span>
                }
                for (int i = 0; i < 5 - item.StarRating; i++)
                {
                    <span>&#x2606;</span>
                }
            }
        </p>

        <p>@Html.DisplayFor(modelItem => item.Feedback)</p>
        <p>Posted by <b>@Html.DisplayFor(modelItem => item.UserName)</b> on @Html.DisplayFor(modelItem => item.Date)</p>


        @if (User.IsInRole("Manager"))
        {
            <a asp-controller="FeedbackPosts" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-light">Delete</a>
            <a asp-controller="FeedbackPosts" asp-action="Edit" asp-route-id="@item.Id"  class="btn btn-light">Edit</a>
        }

        <a asp-controller="FeedbackPosts" asp-action="Details" asp-route-id="@item.Id" class="btn btn-default">Details</a>
        <a asp-controller="FeedbackPosts" asp-action="IncreaseAgree" asp-route-id="@item.Id" class="btn btn-success">Agree(@item.Agree)</a>
        <a asp-controller="FeedbackPosts" asp-action="IncreaseDisagree" asp-route-id="@item.Id" class="btn btn-danger">Disagree(@item.Disagree)</a>
        <hr />
    }
</section>